import { RoomOption } from "../../types/rooms/roomOption";

export const ROOMS : RoomOption[] = [
  { name: "프로젝트 1", value: "PROJECT1", floor: "1" },
  { name: "프로젝트 2", value: "PROJECT2", floor: "1" },
  { name: "프로젝트 3", value: "PROJECT3", floor: "2" },
  { name: "프로젝트 4", value: "PROJECT4", floor: "2" },
  { name: "LAB 1", value: "LAB1", floor: "2" },
  { name: "LAB 2", value: "LAB2", floor: "2" },
  { name: "LAB 3", value: "LAB3", floor: "2" },
  { name: "LAB 4", value: "LAB4", floor: "2" },
  { name: "LAB 5", value: "LAB5", floor: "2" },
  { name: "LAB 6", value: "LAB6", floor: "2" },
  { name: "LAB 7", value: "LAB7", floor: "2" },
  { name: "LAB 8", value: "LAB8", floor: "2" },
  { name: "LAB 9", value: "LAB9", floor: "2" },
  { name: "LAB 10", value: "LAB10", floor: "2" },
  { name: "LAB 11", value: "LAB11", floor: "2" },
  { name: "서버실", value: "SERVER", floor: "2" },
  { name: "프로젝트 5", value: "PROJECT5", floor: "3" },
  { name: "프로젝트 6", value: "PROJECT6", floor: "3" },
  { name: "LAB 12", value: "LAB12", floor: "3" },
  { name: "LAB 13", value: "LAB13", floor: "3" },
  { name: "LAB 14", value: "LAB14", floor: "3" },
  { name: "LAB 15", value: "LAB15", floor: "3" },
  { name: "LAB 16", value: "LAB16", floor: "3" },
  { name: "LAB 17", value: "LAB17", floor: "3" },
  { name: "LAB 18", value: "LAB18", floor: "3" },
  { name: "LAB 19", value: "LAB19", floor: "3" },
  { name: "LAB 20", value: "LAB20", floor: "3" },
  { name: "LAB 21", value: "LAB21", floor: "3" },
  { name: "LAB 22", value: "LAB22", floor: "3" },
  { name: "메이커실", value: "PRINTER_MAKER", floor: "3" },
];