export type AttendStatus =
  | "WINTER_CAMP_LECTURE"
  | "WINTER_CAMP_SELF_STUDY"
  | "CLUB"
  | "CLASS"
  | "NOT_ATTEND"
  | "SLEEPOVER"
  | "OUTGOING"
  | "FIELD_PRACTICE"
  | "NARSHA"
  | "AFTER_SCHOOL"
  | "SHIFT_ATTEND"
  | "OTHER"
  | "INDUSTRY";
