import {Option} from "../../types/props/dropdownProps.ts";

export const ROOMS : Option[] = [
  { name: "프로젝트 1", value: "PROJECT1" },
  { name: "프로젝트 2", value: "PROJECT2" },
  { name: "프로젝트 3", value: "PROJECT3" },
  { name: "프로젝트 4", value: "PROJECT4" },
  { name: "LAB 1", value: "LAB1" },
  { name: "LAB 2", value: "LAB2" },
  { name: "LAB 3", value: "LAB3" },
  { name: "LAB 4", value: "LAB4" },
  { name: "LAB 5", value: "LAB5" },
  { name: "LAB 6", value: "LAB6" },
  { name: "LAB 7", value: "LAB7" },
  { name: "LAB 8", value: "LAB8" },
  { name: "LAB 9", value: "LAB9" },
  { name: "LAB 10", value: "LAB10" },
  { name: "LAB 11", value: "LAB11" },
  { name: "서버실", value: "SERVER" },
  { name: "프로젝트 5", value: "PROJECT5" },
  { name: "프로젝트 6", value: "PROJECT6" },
  { name: "LAB 12", value: "LAB12" },
  { name: "LAB 13", value: "LAB13" },
  { name: "LAB 14", value: "LAB14" },
  { name: "LAB 15", value: "LAB15" },
  { name: "LAB 16", value: "LAB16" },
  { name: "LAB 17", value: "LAB17" },
  { name: "LAB 18", value: "LAB18" },
  { name: "LAB 19", value: "LAB19" },
  { name: "LAB 20", value: "LAB20" },
  { name: "LAB 21", value: "LAB21" },
  { name: "LAB 22", value: "LAB22" },
  { name: "메이커실", value: "PRINTER_MAKER" },
];