import {Option} from "../../types/props/elements/dropdownProps.ts";

export const ROOMS : Option[] = [
  // { name: "프로젝트 1", value: "PROJECT1" },
  // { name: "프로젝트 2", value: "PROJECT2" },
  { name: "프로젝트 3", value: "PROJECT3" },
  { name: "프로젝트 4", value: "PROJECT4" },
  // { name: "LAB 1", value: "LAB1" },
  // { name: "LAB 2", value: "LAB2" },
  // { name: "LAB 3, 4", value: "LAB3_4" },
  // { name: "LAB 5", value: "LAB5" },
  // { name: "LAB 6", value: "LAB6" },
  // { name: "LAB 7", value: "LAB7" },
  // { name: "LAB 8", value: "LAB8" },
  // { name: "LAB 9", value: "LAB9" },
  // { name: "LAB 10", value: "LAB10" },
  // { name: "LAB 11", value: "LAB11" },
  // { name: "서버실", value: "SERVER" },
  { name: "프로젝트 5", value: "PROJECT5" },
  { name: "프로젝트 6", value: "PROJECT6" },
  // { name: "LAB 12", value: "LAB12" },
  // { name: "LAB 13", value: "LAB13" },
  // { name: "LAB 14", value: "LAB14" },
  { name: "LAB 15, 16", value: "LAB15_16" },
  { name: "LAB 17, 18", value: "LAB17_18" },
  { name: "LAB 19, 20", value: "LAB19_20" },
  { name: "LAB 21, 22", value: "LAB21_22" },
  // { name: "메이커실", value: "PRINTER_MAKER" },
];
